module: Freedom
author: Arthur Ariel Sabintsev
author_url: http://www.sabintsev.com
github_url: https://github.com/artsabintsev/freedom
copyright: "© 2017 [Arthur Ariel Sabintsev](http://www.sabintsev.com)"
clean: true
podspec: Freedom.podspec
